// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvancedConfig } from "./AdvancedConfig";
import type { ProcessConfig } from "./ProcessConfig";
import type { RestartConfig } from "./RestartConfig";

export type AppDraft = { name: string, process: ProcessConfig, startupEnabled: boolean, restart: RestartConfig, loggingEnabled: boolean, advanced: AdvancedConfig, };
