// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedApp } from "./ManagedApp";
import type { ServiceStatus } from "./ServiceStatus";

export type AppOverview = { app: ManagedApp, status: ServiceStatus, statusDetail: string | null, };
