// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvironmentVariable } from "./EnvironmentVariable";

export type ProcessConfig = { executable: string, arguments: string, workingDirectory: string, environment: Array<EnvironmentVariable>, };
