// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RestartPolicy } from "./RestartPolicy";

export type RestartConfig = { policy: RestartPolicy, delaySeconds: number, };
