[package]
name = "stayup-windows"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
stayup-core = { path = "../stayup-core" }
uuid = { version = "1.26.1", features = ["serde", "v4"] }
windows = { version = "0.62.2", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Security_Authorization",
  "Win32_Storage_FileSystem",
  "Win32_System_LibraryLoader",
  "Win32_System_IO",
  "Win32_System_Com",
  "Win32_System_Registry",
  "Win32_System_SystemInformation",
  "Win32_System_Pipes",
  "Win32_System_Services",
  "Win32_System_Threading",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
] }
